apiVersion: v1
kind: ResourceQuota
metadata:
  name: bc-prod-quota
  namespace: bc-prod
spec:
  hard:
    limits.cpu: 1000m
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cc-prod-quota
  namespace: cc-prod
spec:
  hard:
    limits.cpu: 1000m
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cc-prod-quota
  namespace: pc-prod
spec:
  hard:
    limits.cpu: 1000m
    limits.memory: 2Gi
